### ISSUE TITLE
Weirder Pfeil nach Startseite

### ISSUE THREAD

**Issue by Maihoernchen** [gruener-campus-malchow/gcmofficial#13]
![image](https://user-images.githubusercontent.com/72254540/205332504-03bcaae0-003f-465e-bad1-1d67e64e4332.png)

**Comment by Maihoernchen** [comment]
ist sonst nicht da ihr deppen

**Comment by Maihoernchen** [comment]
wenn ihr den issue hier closed before der resolved ist dann bau ich wirklich sexshrek ein

**Comment by Maihoernchen** [comment]
![Bildschirmfoto zu 2022-12-02 16-57-12](https://user-images.githubusercontent.com/72254540/205333911-81a2935b-624d-48b9-9ac4-e50e783444bb.png)

**Comment by NoYavy** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/66779682/213583313-594212f3-6891-4419-9c93-5e8e6c498cb9.png)
