### ISSUE TITLE
inconsistent slideshow speed + starting white

### ISSUE THREAD

**Issue by TenkouNoKitsune** [gruener-campus-malchow/gcmofficial#22]
The first image fades in from a white background, also the speed of the animation changes.
(the speed issue seems to be connected to clicking)

https://user-images.githubusercontent.com/66779682/213573528-bfcfffb3-4bdf-49e4-b0c0-2649048cefff.mp4

_Originally posted by @NoYavy in https://github.com/gruener-campus-malchow/gcmofficial/pull/18#discussion_r1081924635_

**Comment by Maihoernchen** [comment]
Irgendwann gefixt, funzt jetzt jedenfalls

**Comment by NoYavy** [comment]
ne

**Comment by Maihoernchen** [comment]
traced the origin to the interval clear, fixin it in a couple days

**Comment by Maihoernchen** [comment]
seems to be fixed please reopen if persists, only tested on 2 machines so far
