### ISSUE TITLE
Kurzmeldungen sehen scuffed aus

### ISSUE THREAD

**Issue by Maihoernchen** [gruener-campus-malchow/gcmofficial#36]
* weißer Rand oben
* Text ganz rechts kein Hintergrund

![image](https://github.com/gruener-campus-malchow/gcmofficial/assets/72254540/b99ff980-f2a0-42dd-a45c-29fa864731d7)

**Comment by TenkouNoKitsune** [comment]
Der weiße Rand ist Absicht um die Kurzmeldungen von dem Rest der Seite beim scrollen unterscheiden zu können (besonders aufgrund des gleich gefärbten `<aside>`-Elements)

**Comment by TenkouNoKitsune** [comment]
Zu "Text rechts kein Hintergrund":

Der Hintergrund ist genauso lang wie der Bildschirm selbst. Da der Text rechts aus dem Bildschirm heraus ragt, ist dort auch kein Hintergrund.

Die Animation liegt zurzeit auf `.view-content` also auf dem gesamten Element. Stattdessen sollten sich die `.views-row` Elemente bewegen. Übrigens nur jene im Element `.view-kurzmeldungen`, da das sonst auf all Views auf der Seite zutrifft.

**Comment by TenkouNoKitsune** [comment]
Die Lösung ist am einfachsten mit **JavaScript** umzusetzen.

Und sollte folgendes ermöglichen:

Alle angesprochenen Elemente bewegen sich
- gleichmäßig
- nach links
Sobald das Element links aus dem Bildschirm verschwunden ist, soll es
- entfernt werden
- am Ende der Liste von Einträgen/Elementen wieder eingefügt werden
- sich wieder nach links bewegen

**Comment by TenkouNoKitsune** [comment]
Die Liste von Einträgen/Elementen hat eine unbestimmte Länge

**Comment by TenkouNoKitsune** [comment]
Aus Gründen der Barrierefreiheit:

 Bitte (doch) **keinen** rechts-nach-links scroll-Effekt, anstatt dessen:
1. Nach gewisser Zeit soll das erste Element der Kurzmeldungen-Liste verschwinden
2. Die restlichen Elemente sollen nachrücken
3. Das entfernte Element dann am Ende der Liste wieder angefügen

Umsetzung ist mit JavaScript möglich.

Achtung: Die Liste von Einträgen/Elementen hat eine unbestimmte Länge.

**Comment by NoYavy** [comment]
Weiteres Problem, alle Neuigkeiten bewegen sich und das grüne Band hat ein sich bewegendes Ende, anstatt am Bildschirmrand zu verbleiben:

https://github.com/gruener-campus-malchow/gcmofficial/assets/66779682/119f3004-f48e-4e2d-a372-9f6fed30a708

**Comment by TenkouNoKitsune** [comment]
> Weiteres Problem, alle Neuigkeiten bewegen sich und das grüne Band hat ein sich bewegendes Ende, anstatt am Bildschirmrand zu verbleiben:
> 
> https://github.com/gruener-campus-malchow/gcmofficial/assets/66779682/119f3004-f48e-4e2d-a372-9f6fed30a708
> 
> 

Siehe Kommentar 2 für Gründe/Lösung

**Comment by TenkouNoKitsune** [comment]
> Aus Gründen der Barrierefreiheit:
> 
>  Bitte (doch) **keinen durchgängigen** rechts-nach-links scroll-Effekt, anstatt dessen:
> 
> _V1)_
> 
> 1. Nach gewisser Zeit soll das erste Element der Kurzmeldungen-Liste verschwinden (Nicht zwingend mit Animation aber möglich)
> 2. Die restlichen Elemente sollen nachrücken (nicht zwingend mit Animation aber möglich)
> 3. Das entfernte Element dann am Ende der Liste wieder angefügen
> 4. Für gewisse Zeit pausieren, Elemente stehen still
> 5. Vorgang wiederholen
> 
> _V2)_
> 
> Auch möglich wäre,
> 1. dass sich alle Elemente solange nach links bewegen bis das erste Element vollständig links neben dem Bildschirmrand liegt
> 2. anschließend das erste Element von vorne entfernt und hinten wieder angefügt wird
> 3. und dann die Animation für angemessene Zeit pausiert (Elemente stehen still), bis der Vorgang wiederholt wird
> 
> Umsetzung ist mit JavaScript möglich.
> 
> Achtung: Die Liste von Einträgen/Elementen hat eine unbestimmte Länge.

Wir könnten auch überlegen, die Kurzmeldungen als Slideshow auszugeben und dessen Code auch für die Kurzmeldungen mitzunutzen ... (?)
