### ISSUE TITLE
Schriftgröße skaliert mit Fensterbreite

### ISSUE THREAD

**Issue by mojansch** [gruener-campus-malchow/gcmofficial#5]
Momentan skaliert die gesamte Seite mit der Fensterbreite, dadurch ist auf höchauflösenden Monitoren die Schrift riesig und bei schmalen Fenstern winzig. Außerdem entstehen interessante Anzeigefehler (siehe Screenshots). Ein Wechsel der Schriftgrößeneinheit von vw auf bspw. em würde das beheben.
![image](https://user-images.githubusercontent.com/18553858/192833071-d26d8e2c-ab64-4039-ae41-fc4b2cc186d1.png)
![image](https://user-images.githubusercontent.com/18553858/192833100-4e6a83b1-bf16-4a7e-aa43-b3d55abab13e.png)
![image](https://user-images.githubusercontent.com/18553858/192833006-16bdb539-74ee-4fb6-ac97-99279c167870.png)

**Comment by TenkouNoKitsune** [comment]
Der Anzeigefehler sollte nun behoben sein und die Schriftgröße skaliert nun nicht mehr mit der Fensterbreite: siehe Commit `b6e348d59bc1074db6001a10751f78fab30529c8`
